rootProject.name = "potatocloud"
include("api")
include("connector")
include("node")
include("core")
include("server-plugins")
include("server-plugins:cloudcommand")
include("server-plugins:hub")
include("server-plugins:labymod")
include("server-plugins:notify")
include("server-plugins:proxy")
include("server-plugins:shared")
include("platform-plugins")
include("platform-plugins:limbo")
include("platform-plugins:spigot-legacy")
include("platform-plugins:velocity")
include("platform-plugins:spigot")
include("common")