permission: "potatocloud.proxy"
command-aliases:
  - maintenance
maintenance-bypass-permission: "potatocloud.maintenance.bypass"
useTablistBanner: false # Only works with Labymod
tablistImageURL: "https://imgur.com/TGofXh8.png%22" # Only works with Labymod. "%22" is the Size of the Banner.
useTablist: true
useMotd: true
whitelist:
  - ExamplePlayer1
  - ExamplePlayer2
maintenance: false
tablist:
  header: " \n                      <dark_gray>» <gradient:#55FF55:#DAF3DA>potatocloud</gradient> <dark_gray>«                      \n<dark_gray>• <gray>Server<dark_gray>: <green>%service% <dark_gray>| <gray>Online<dark_gray>: <green>%online_players% <dark_gray>•\n "
  footer: "\n<dark_gray>• <gray>contributors <dark_gray>•\n<white>jirmjahu, TruaYT, einCode_\n "
# %service%, %group%, %proxy%, %online_players%, %max_players%

motd:
  default:
    firstLine: "<dark_gray>» <gradient:#55FF55:#DAF3DA>potatocloud</gradient> <dark_gray>• <gray>Powered by potatoes <dark_gray>• <white>1.21+"
    secondLine: "                   <green>We are online"
  maintenance:
    firstLine: "<dark_gray>» <gradient:#55FF55:#DAF3DA>potatocloud</gradient> <dark_gray>• <gray>Powered by potatoes <dark_gray>• <white>1.21+"
    secondLine: "                  <red>We are in maintenance"
    version: "<red>Maintenance"
